### ISSUE TITLE
"private dns server cannot be accessed" on Android

### ISSUE THREAD

**Issue by cubagithub** [mullvad/dns-adblock#17] opened 2021-11-22 11:42 UTC
Hello. 

I'm connected to Mullvad via wireguard in Android 11, and have Private DNS configured to `adblock.doh.mullvad.net` as per https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

I receive the messages **"private dns server cannot be accessed"** **"mobile network has no internet access"** despite being able to resolve the DNS endpoint's hostname, and connectivity actually being fine.

**Question:** Is a Google/Android connectivity checker blocked by an entry in these lists?

#### Private DNS
![private_DNS](https://user-images.githubusercontent.com/34730232/142853339-cfe95d2c-172d-4a35-9782-d5f5c8af4d95.png)

#### Connectivity check lookup
![connectivitycheck](https://user-images.githubusercontent.com/34730232/142855096-609d4c54-1519-40ed-873c-d4e113e99864.png)

#### Mobile network has no internet access: Private DNS server cannot be accessed
![DNS_Error](https://user-images.githubusercontent.com/34730232/142856070-984698fd-5da7-4f1b-b5d1-7eeb3cd803b7.png)

#### Mullvad connection check
![mullvad_check](https://user-images.githubusercontent.com/34730232/142853707-200b808e-3f47-42b9-aab5-06a1c171918e.png)

#### DOH server lookup
![DNS_lookup](https://user-images.githubusercontent.com/34730232/142854948-7b4de182-f205-4190-bd44-068843c679e4.png)

**Comment by oskaralmlov** [comment] 2021-12-08 11:13
Hi, thanks for reaching out. 

I had a look at this and from what I'm seeing that specific domain is not blocked from being resolved. I did a quick google search and there appears to be multiple domain that are used for this check depending on which android version you're using. I tried a couple but I can't see that they're being blocked:
```
$ dig connectivitycheck.gstatic.com connectivitycheck.android.com  @adblock.doh.mullvad.net +short
216.58.207.227
142.250.74.78
```

So going by the results when resolving the domain you provided and the one I found it appears we're not blocking any of them. 

Should you need further help with troubleshooting this specific issue it's better to contact our support team (support@mullvad.net). They have more experience with dealing with these kind of issues and have access to devices on which they can reproduce the issue.

Have a good one!

**Comment by xanoni** [comment] 2022-03-26 22:56
Any updates on this? Seeing the same error message on a stock Android 12 device. Both AdBlock and non-adblock DOH affected. Using Mullvad VPN app.

WiFi indicator in top right of screen shows exclamation mark.

Addresses resolve. Connection check succeeds.

`
<p>Your DNS requests originate from:</p><div class="q-mb-lg">

IP Address | 89.46.62.132
-- | --
us-nyc-dns-201
M247
USA

</div>
`

**Comment by oskaralmlov** [comment] 2022-03-29 08:21
> Any updates on this? Seeing the same error message on a stock Android 12 device. Both AdBlock and non-adblock DOH affected. Using Mullvad VPN app.
> 
> WiFi indicator in top right of screen shows exclamation mark.
> 
> Addresses resolve. Connection check succeeds.
> 
> ```
> Your DNS requests originate from:
> 
> IP Address 89.46.62.132
> us-nyc-dns-201
> M247
> USA
> ```
> 
> Edit: exclamation mark seems transitory... It disappeared now.

Hi!

For how long was the issue ongoing? An approximate of the time it started and when it went away would be great to know.
Also, did you change which relay you were connected to during this time? If yes; did it help with making the issue go away and to which relay did you change?

Thanks.

**Comment by xanoni** [comment] 2022-05-08 23:48
I no longer have this information, and I no longer have the same issue.

However, I noticed that on one specific WiFi, Android tells me that the WiFi doesn't provide Internet, while it does.

But could be anything, so would say for now that this issue no longer affects me.

**Closed** 2022-05-10 08:57 UTC

**Comment by Dyrimon** [comment] 2023-07-26 04:16
@oskaralmlov Hi, I'm facing the same issue on android 11. I tested other ad-blocking dns servers (controlD) and they work properly. Mullvad dns cannot be connected to when using DoT in the private DNS settings.

**Comment by Yolakalemowa** [comment] 2025-03-16 13:54
I'm facing this issue too. Can we re-open the issue?

I'm getting a "private dns server cannot be accessed". Using the base.dns.mullvad.net one on my android btw.

**Comment by Ciancy28** [comment] 2026-01-15 14:36
I'll add myself to the list of people affected by this.
I've been struggling with losing internet access in 30-60 second windows for months now and sure enough, I get "DNS cannot be accessed" when that happens (I had to check through settings because the notification doesn't seem to work on my device for some probably unrelated reason) and disabling private dns brings connectivity back up.

**Comment by mpfaff** [comment] 2026-05-03 14:44
I've also been experiencing this issue almost constantly when connected to Wi-Fi.
